### ISSUE TITLE
[Bug]: Needs updating for 1.21.3?

### ISSUE THREAD

**Issue by puppie1997** [tristankechlo/FullGrownCropMarker#3]
### What happened?

Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'crop_marker' at 'com.tristankechlo.crop_marker.FabricFullGrownCropMarker'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:482)
	at knot//net.minecraft.client.main.Main.main(Main.java:248)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalAccessError: class com.tristankechlo.crop_marker.config.FullGrownCropMarkerConfig tried to access private method 'void net.minecraft.class_2960.<init>(java.lang.String, java.lang.String)' (com.tristankechlo.crop_marker.config.FullGrownCropMarkerConfig and net.minecraft.class_2960 are in unnamed module of loader 'knot' @62e136d3)
	at knot//com.tristankechlo.crop_marker.config.FullGrownCropMarkerConfig.getID(FullGrownCropMarkerConfig.java:66)
	at knot//com.tristankechlo.crop_marker.config.FullGrownCropMarkerConfig.createOptions(FullGrownCropMarkerConfig.java:55)
	at knot//com.tristankechlo.crop_marker.config.FullGrownCropMarkerConfig.<clinit>(FullGrownCropMarkerConfig.java:19)
	at knot//com.tristankechlo.crop_marker.config.ConfigManager.loadAndVerifyConfig(ConfigManager.java:31)
	at knot//com.tristankechlo.crop_marker.FullGrownCropMarker.init(FullGrownCropMarker.java:21)
	at knot//com.tristankechlo.crop_marker.FabricFullGrownCropMarker.onInitializeClient(FabricFullGrownCropMarker.java:11)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more

### Minecraft Version

1.21.3

### Modversion

1.20.4

### Modloader

Fabric

### Additional context

Love this mod! Would love to use it for 1.20.3! Thank you!

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Yeah, definitly needs an update.  
Last update was for 1.20.4, I am surprised it even worked that long

**Comment by tristankechlo** [comment]
Closing, as there is a modversion for 1.21.3 available
